[package]
name = "cad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.2"
image = "0.24.7"
imageproc = "*"
rusttype = "*"
mematrica = "0.2.2"